---
# vars file for docker

_python_pip_packages:
  Alpine:
    - py3-pip
    - py3-setuptools
    - python3-dev
  Debian:
    - python3-pip
    - python3-setuptools
  RedHat-7:
    - python2-pip
    - python-setuptools
  RedHat:
    - python3-pip
    - python3-setuptools
  Suse:
    - python-pip
    - python-setuptools

python_pip_packages: "{{ _python_pip_packages[ansible_os_family ~ '-' ~ ansible_distribution_major_version] | default(_python_pip_packages[ansible_os_family] | default(_python_pip_packages['default'])) }}"

_docker_packages:
  default:
    - docker
    - docker-compose
  Alpine:
    - docker
  RedHat-7:
    - docker-io
    - docker-compose
  RedHat-8:
    - podman-docker
  Debian:
    - docker.io
    - docker-compose

docker_packages: "{{ _docker_packages[ansible_os_family ~ '-' ~ ansible_distribution_major_version] | default(_docker_packages[ansible_os_family] | default(_docker_packages['default'])) }}"

docker_pip_packages:
  - docker
  - docker-compose

_docker_service:
  default: docker
  RedHat-8: io.podman

docker_service: "{{ _docker_service[ansible_os_family ~ '-' ~ ansible_distribution_major_version] | default(_docker_service['default']) }}"

_docker_socket:
  default: /var/run/docker.sock
  RedHat-8: /var/run/podman/io.podman

docker_socket: "{{ _docker_socket[ansible_os_family ~ '-' ~ ansible_distribution_major_version] | default(_docker_socket['default']) }}"
