---
- name: gets my public IP
  ipify_facts:
  register: myip
- name: set my public ip into facts
  set_fact:
    "{{item.name}}": "{{item.value}}"
  with_items:
  - {name: "public_ip", value: "{{myip.ansible_facts.ipify_public_ip}}"}
- name: set ssh firewall rule into facts
  set_fact:
    ssh_fwrule: [{protocol: "ssh", port: "tcp:22", src: "{{public_ip}}/32"}]
- name: creates network
  local_action:
    module: gce_net
    name: "{{hostname}}-net"
    mode: auto
    state: present
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
- name: creates inbound firewall rules
  local_action:
    module: gce_net
    name: "{{hostname}}-net"
    fwname: "inbound-{{item.protocol}}"
    allowed: "{{item.port}}"
    state: present
    src_range: ["{{item.src}}"] 
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
  with_items: "{{open_ports}} + {{ssh_fwrule}}"
- name: creates external IP
  local_action:
    module: gce_eip
    name: "{{hostname}}-ip"
    region: "{{region}}"
    state: present
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
- name: creates gce engine
  local_action:
    module: gce
    instance_names: "{{hostname}}"
    zone: "{{zone}}"
    machine_type: "{{machine_type}}"
    external_ip: "{{hostname}}-ip"
    network: "{{hostname}}-net"
    state: present
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
  register: instance
- name: saves host data
  add_host:
    hostname: "{{ instance.instance_data[0].public_ip }}"
    groupname: gce_instance
    ansible_ssh_private_key_file: "{{ansible_ssh_private_key_file}}"
- name: waits for ssh to be available
  wait_for:
    delay: 1
    host: "{{ instance.instance_data[0].public_ip }}"
    port: 22
    state: started
    timeout: 30
